### ISSUE TITLE
'PRIMER_PAIR_NUM_RETURNED' is not in list error

### ISSUE THREAD

**Issue by bhagesh-h** [phenotypic/Primer-Designer#1]
I am trying to design primers for **DARS2** gene in Homo Sapiens, while using the given script I encountered the following error:

```
Enter index of parameter to edit or press return:
Traceback (most recent call last):
  File "designer.py", line 144, in <module>
    pair_count = int(output[output.index('PRIMER_PAIR_NUM_RETURNED')+1])
ValueError: 'PRIMER_PAIR_NUM_RETURNED' is not in list
```

Please let me know if there is any way to rectify this.

Thank you.

**Comment by phenotypic** [comment]
Hi there, I can confirm that I also receive this error when selecting `human` as species and `dars2` as the gene.

The error is generated because the script is unable to find any exon sequences which occur across all 13 splice variants. The script outputs this message before you receive the error message:

```
Found 0 overlapping sequences to search
```

You can see this for yourself if you look at [the Ensembl page for this gene](https://ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000117593;r=1:173824653-173858808).

There is no perfect solution to this issue. However, in the near future I intend to add a feature where the user can manually select a handful of splice variants to find overlaps for.

**Comment by phenotypic** [comment]
In the latest version of the script, I've added a feature where you can manually select splice variants if no overlaps are found across all splice variants. I hope this helps :)
